version: 2

sources:
  - name: jaffle_shop
    schema: jaffle_shop  
    tables:
      - name: orders
        columns:
          - name: id
            tests:
              - unique
              - not_null
      - name: customers
      - name: payments